-- Track Workers AI usage generated by this application.
-- This is an app-side estimate of Cloudflare's daily Neuron consumption; the
-- Cloudflare dashboard remains authoritative for account-wide usage.

create table if not exists public.llm_usage (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    provider text not null,
    model text not null,
    input_tokens integer not null check (input_tokens >= 0),
    output_tokens integer not null check (output_tokens >= 0)
);

create index if not exists llm_usage_created_at_idx
    on public.llm_usage (created_at desc);

alter table public.llm_usage enable row level security;
revoke all on table public.llm_usage from anon, authenticated;

create or replace function public.record_cloudflare_usage(
    p_model text,
    p_input_tokens integer,
    p_output_tokens integer
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    if p_model is null or length(p_model) > 200 then
        raise exception 'invalid model';
    end if;
    if p_input_tokens < 0 or p_input_tokens > 1000000 then
        raise exception 'invalid input token count';
    end if;
    if p_output_tokens < 0 or p_output_tokens > 1000000 then
        raise exception 'invalid output token count';
    end if;

    insert into public.llm_usage(provider, model, input_tokens, output_tokens)
    values ('cloudflare', p_model, p_input_tokens, p_output_tokens);
end;
$$;

create or replace function public.cloudflare_usage_today()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
    select jsonb_build_object(
        'calls', count(*),
        'input_tokens', coalesce(sum(input_tokens), 0),
        'output_tokens', coalesce(sum(output_tokens), 0)
    )
    from public.llm_usage
    where provider = 'cloudflare'
      and created_at >= date_trunc('day', now() at time zone 'UTC') at time zone 'UTC';
$$;

grant execute on function public.record_cloudflare_usage(text, integer, integer)
    to anon, authenticated;
grant execute on function public.cloudflare_usage_today()
    to anon, authenticated;
grant execute on function public.record_cloudflare_usage(text, integer, integer)
    to service_role;
grant execute on function public.cloudflare_usage_today()
    to service_role;
